kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: mcr.microsoft.com/dotnet/core/sdk:2.1
  commands:
  - cd AspNetCore.Docker/AspNetCore.Docker
  - dotnet build -c Release -o /build
  - dotnet publish -c Release -o /app

---
kind: pipeline
name: publish

platform:
  os: linux
  arch: amd64

steps:
- name: publish
  image: plugins/docker
  settings:
    repo: v7lin/blog-aspnet
    context: AspNetCore.Docker
    dockerfile: AspNetCore.Docker/AspNetCore.Docker/Dockerfile
    target: prod
    username:
      from_secret: REGISTRY_USER
    password:
      from_secret: REGISTRY_PASSWORD
    tags:
    - ${DRONE_TAG}
    - latest

trigger:
  status:
  - success
  event:
  - tag

depends_on:
- build
